<?php
declare(strict_types=1);
date_default_timezone_set('Asia/Taipei');
header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store');
$dataFile = dirname(__DIR__) . '/json/wallpaper-stats.json'; $seedFile = dirname(__DIR__) . '/json/wallpaper-stats.seed.json';
function respond(array $payload, int $status = 200): never { http_response_code($status); echo json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); exit; }
function clientId(mixed $value): string { return substr(preg_replace('/[^a-zA-Z0-9_-]/', '', (string) $value) ?? '', 0, 80); }
function ratingData(array &$item): array { $ratings = is_array($item['ratings'] ?? null) ? $item['ratings'] : []; $sum = array_sum(array_map('intval', $ratings)); $count = count($ratings); $item['rating_sum'] = $sum; $item['rating_count'] = $count; $item['rating_average'] = $count ? round($sum / $count, 1) : 0; return [$sum, $count, $item['rating_average']]; }
if (!is_file($dataFile) && is_file($seedFile)) copy($seedFile, $dataFile);
$handle = fopen($dataFile, 'c+'); if (!$handle) respond(['ok' => false, 'error' => '統計資料暫時無法使用。'], 500);
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET'; if (!flock($handle, $method === 'POST' ? LOCK_EX : LOCK_SH)) respond(['ok' => false, 'error' => '統計資料忙碌中。'], 503);
rewind($handle); $store = json_decode(stream_get_contents($handle) ?: '{}', true); if (!is_array($store)) $store = []; $store['wallpapers'] ??= [];
$catalog = json_decode((string) @file_get_contents(dirname(__DIR__) . '/json/wallpapers.json'), true);
foreach (($catalog['wallpapers'] ?? []) as $wallpaper) { $id = (string) ($wallpaper['id'] ?? ''); if ($id !== '' && !isset($store['wallpapers'][$id])) $store['wallpapers'][$id] = ['likes'=>0,'dislikes'=>0,'downloads'=>0,'views'=>0,'votes'=>[],'ratings'=>[]]; }
if ($method === 'GET') { $client = clientId($_GET['client_id'] ?? ''); $week=date('o-W'); $preferences=json_decode((string)@file_get_contents(dirname(__DIR__).'/json/user-preferences.json'),true); $favoriteCounts=[]; foreach (($preferences['users']??[]) as $profile) foreach (($profile['favorites']??[]) as $favoriteId) $favoriteCounts[(string)$favoriteId]=($favoriteCounts[(string)$favoriteId]??0)+1; $public=[]; $votes=[]; foreach ($store['wallpapers'] as $id => &$item) { [,,$average]=ratingData($item); $public[$id]=['likes'=>(int)($item['likes']??0),'dislikes'=>(int)($item['dislikes']??0),'downloads'=>(int)($item['downloads']??0),'views'=>(int)($item['views']??0),'weekly_views'=>($item['views_week']??'')===$week?(int)($item['weekly_views']??0):0,'favorites'=>(int)($favoriteCounts[(string)$id]??0),'rating_average'=>$average,'rating_count'=>(int)$item['rating_count'],'auto_hidden'=>!empty($item['auto_hidden'])]; if ($client !== '' && in_array($item['votes'][$client]??null,['like','dislike'],true)) $votes[$id]=$item['votes'][$client]; } unset($item); flock($handle,LOCK_UN); fclose($handle); respond(['ok'=>true,'updated_at'=>$store['updated_at']??null,'wallpapers'=>$public,'user_votes'=>$votes]); }
if ($method !== 'POST') { flock($handle,LOCK_UN); fclose($handle); respond(['ok'=>false,'error'=>'不支援的請求方式。'],405); }
$input=json_decode(file_get_contents('php://input') ?: '{}',true); $id=(string)($input['id']??''); $action=(string)($input['action']??''); $client=clientId($input['client_id']??'');
if (!isset($store['wallpapers'][$id])) { flock($handle,LOCK_UN); fclose($handle); respond(['ok'=>false,'error'=>'找不到桌布。'],404); }
if (!in_array($action,['like','dislike','view','download','rate'],true)) { flock($handle,LOCK_UN); fclose($handle); respond(['ok'=>false,'error'=>'不支援的統計動作。'],422); }
$item =& $store['wallpapers'][$id]; $currentVote=null;
if ($action === 'view' || $action === 'download') { $field=$action==='view'?'views':'downloads'; $item[$field]=(int)($item[$field]??0)+1; if ($action==='view') { $week=date('o-W'); if (($item['views_week']??'')!==$week) { $item['views_week']=$week; $item['weekly_views']=0; } $item['weekly_views']=(int)($item['weekly_views']??0)+1; } }
elseif ($action === 'rate') { $rating=filter_var($input['rating']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>100]]); if ($client==='' || $rating===false) { flock($handle,LOCK_UN); fclose($handle); respond(['ok'=>false,'error'=>'請提供 0 到 100 的有效評分。'],422); } $item['ratings'] = is_array($item['ratings']??null)?$item['ratings']:[]; $item['ratings'][$client]=$rating; [, $count, $average]=ratingData($item); if ($count>=3 && $average<60) { $item['low_rating_since'] ??= date(DATE_ATOM); if (strtotime((string)$item['low_rating_since']) <= strtotime('-7 days')) $item['auto_hidden']=true; } else { unset($item['low_rating_since'],$item['auto_hidden']); } }
else { if ($client==='') { flock($handle,LOCK_UN); fclose($handle); respond(['ok'=>false,'error'=>'請先建立瀏覽器識別。'],422); } $item['votes']=is_array($item['votes']??null)?$item['votes']:[]; $previous=$item['votes'][$client]??null; if ($previous===$action) { $item[$action==='like'?'likes':'dislikes']=max(0,(int)($item[$action==='like'?'likes':'dislikes']??0)-1); unset($item['votes'][$client]); } else { if (in_array($previous,['like','dislike'],true)) $item[$previous==='like'?'likes':'dislikes']=max(0,(int)($item[$previous==='like'?'likes':'dislikes']??0)-1); $item[$action==='like'?'likes':'dislikes']=(int)($item[$action==='like'?'likes':'dislikes']??0)+1; $item['votes'][$client]=$action; $currentVote=$action; } }
ratingData($item); $store['updated_at']=date(DATE_ATOM); rewind($handle); ftruncate($handle,0); $written=fwrite($handle,json_encode($store,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); fflush($handle); flock($handle,LOCK_UN); fclose($handle); if ($written===false) respond(['ok'=>false,'error'=>'無法儲存統計資料。'],500);
respond(['ok'=>true,'id'=>$id,'vote'=>$currentVote,'stats'=>['likes'=>(int)($item['likes']??0),'dislikes'=>(int)($item['dislikes']??0),'downloads'=>(int)($item['downloads']??0),'views'=>(int)($item['views']??0),'weekly_views'=>($item['views_week']??'')===date('o-W')?(int)($item['weekly_views']??0):0,'rating_average'=>(float)$item['rating_average'],'rating_count'=>(int)$item['rating_count'],'auto_hidden'=>!empty($item['auto_hidden'])]]);
